#!/usr/bin/env bash
# PAI-Orbit — Codex CLI adapter generator
#
# Generates AGENTS.md from commands/*.md and skills/*/SKILL.md.
# Only files with codex.include_in_agents_md: true are included.
#
# Usage (from any directory):
#   /path/to/pai-orbit/scripts/generate-codex.sh
#       → writes AGENTS.md to pai-orbit root
#
#   /path/to/pai-orbit/scripts/generate-codex.sh --output-dir /path/to/project
#       → writes AGENTS.md to target project root

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PAI_ORBIT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_FILE="${PAI_ORBIT_DIR}/AGENTS.md"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output-dir)
            OUTPUT_FILE="${2%/}/AGENTS.md"
            shift 2
            ;;
        *)
            printf "Unknown argument: %s\n" "$1" >&2
            exit 1
            ;;
    esac
done

# ── YAML front-matter parsers ─────────────────────────────────────────────────

yaml_scalar() {
    local key="$1" file="$2"
    awk -v k="${key}:" '
        /^---$/ { c++; if (c == 2) exit; next }
        c == 1 && substr($0, 1, length(k)) == k {
            v = substr($0, length(k) + 1)
            gsub(/^ +| +$/, "", v)
            gsub(/^'"'"'|'"'"'$|^"|"$/, "", v)
            print v; exit
        }
    ' "$file"
}

yaml_codex_field() {
    local field="$1" file="$2"
    awk -v f="  ${field}:" '
        /^---$/ { c++; if (c == 2) exit; next }
        c == 1 && /^codex:/ { in_c = 1; next }
        in_c && substr($0, 1, length(f)) == f {
            v = substr($0, length(f) + 1)
            gsub(/^ +| +$/, "", v)
            gsub(/^'"'"'|'"'"'$|^"|"$/, "", v)
            print v; exit
        }
        in_c && /^[^ ]/ { in_c = 0 }
    ' "$file"
}

get_body() {
    awk '/^---$/ { c++; if (c == 2) { found = 1; next } } found { print }' "$1"
}

# Return ## Codex section if present, else full body
get_codex_content() {
    local body
    body=$(get_body "$1")
    if echo "$body" | grep -q "^## Codex$"; then
        echo "$body" | awk '
            /^## Codex$/ { found = 1; next }
            found && /^## [A-Z]/ { exit }
            found { print }
        '
    else
        echo "$body"
    fi
}

# ── Collect files into two arrays ────────────────────────────────────────────

declare -a MODE_FILES=()
declare -a SKILL_FILES=()

for f in "$PAI_ORBIT_DIR"/commands/*.md; do
    include=$(yaml_codex_field "include_in_agents_md" "$f")
    [[ "$include" == "true" ]] && MODE_FILES+=("$f")
done

for f in "$PAI_ORBIT_DIR"/skills/*/SKILL.md; do
    include=$(yaml_codex_field "include_in_agents_md" "$f")
    [[ "$include" == "true" ]] && SKILL_FILES+=("$f")
done

# ── Build output ──────────────────────────────────────────────────────────────

{

# ── Header ────────────────────────────────────────────────────────────────────
cat << 'HEADER'
<!--
  AGENTS.md — PAI-Orbit agent instructions for Codex CLI
  Generated by scripts/generate-codex.sh. Do not edit by hand.
  To regenerate: /path/to/pai-orbit/scripts/generate-codex.sh --output-dir .
-->

# PAI-Orbit — Agent Instructions

PAI-Orbit is a structured SDLC methodology. It defines **modes** (focused working headspaces) and **skills** (multi-step operational procedures). Follow the active mode's rules until the user explicitly switches.

**To enter a mode:** user says "enter build mode", "use design mode", `/build`, `/design`, etc.
**To invoke a skill:** user says "run git skill", "/git", "/deploy", etc.

---

## Quick Reference

HEADER

# ── Mode summary table ────────────────────────────────────────────────────────
printf "### Modes\n\n"
printf "| Mode | When to use | Writes to |\n"
printf "|------|-------------|----------|\n"

declare -A MODE_OUTPUT
MODE_OUTPUT[arch]="docs/architecture/, docs/decisions/"
MODE_OUTPUT[build]="Code, docs/domain/product-capabilities.md"
MODE_OUTPUT[data]="docs/reports/"
MODE_OUTPUT[design]="docs/features/*/design.md, docs/decisions/"
MODE_OUTPUT[domain]="docs/domain/"
MODE_OUTPUT[groom]="docs/features/*/requirements.md"
MODE_OUTPUT[plan]="docs/plans/"
MODE_OUTPUT[ux]="docs/features/*/ux.md"

for f in "${MODE_FILES[@]}"; do
    name=$(yaml_scalar "name" "$f")
    title=$(yaml_codex_field "section_title" "$f")
    out="${MODE_OUTPUT[$name]:-—}"
    # Extract the first sentence of the description as a short summary
    desc=$(yaml_scalar "description" "$f" | sed 's/\. .*//')
    printf "| \`/%s\` | %s | %s |\n" "$name" "$desc" "$out"
done

printf "\n"

# ── Skill summary table ───────────────────────────────────────────────────────
printf "### Skills\n\n"
printf "| Skill | When to invoke |\n"
printf "|-------|---------------|\n"

for f in "${SKILL_FILES[@]}"; do
    name=$(yaml_scalar "name" "$f")
    # Extract the TRIGGER portion of the description
    desc=$(yaml_scalar "description" "$f" | sed 's/.*TRIGGER/TRIGGER/' | sed 's/SKIP.*//' | sed 's/^ *//')
    printf "| \`/%s\` | %s |\n" "$name" "$desc"
done

printf "\n%s\n\n" "---"

# ── Modes — full content ──────────────────────────────────────────────────────
printf "## Modes\n\n"

for f in "${MODE_FILES[@]}"; do
    name=$(yaml_scalar "name" "$f")
    title=$(yaml_codex_field "section_title" "$f")
    content=$(get_codex_content "$f")
    printf -- "---\n\n"
    printf "### %s\n\n" "$title"
    printf "%s\n\n" "$content"
done

# ── Skills — full content ─────────────────────────────────────────────────────
printf -- "---\n\n"
printf "## Skills\n\n"

for f in "${SKILL_FILES[@]}"; do
    name=$(yaml_scalar "name" "$f")
    title=$(yaml_codex_field "section_title" "$f")
    content=$(get_codex_content "$f")
    printf -- "---\n\n"
    printf "### %s\n\n" "$title"
    printf "%s\n\n" "$content"
done

# ── Project configuration note ────────────────────────────────────────────────
cat << 'FOOTER'
---

## Project Configuration

Read `.claude/pai-orbit-config.md` at the start of every session.

If a `## System Docs` section is present:
- **Relative path:** check if the directory exists. If yes, read docs from `<system_docs_repo>/<system_docs_path>` in addition to local `docs/`. If unreachable, warn once and continue.
- **Git URL:** the repo must be cloned locally before commands can read from it. Warn if absent.

Read `CLAUDE.md` for project architecture, stack, conventions, and key file locations.

If `docs/architecture/constraints.md` exists, read it before generating any code — treat violations as blocking.
FOOTER

} > "$OUTPUT_FILE"

# ── Summary ───────────────────────────────────────────────────────────────────
mode_count=${#MODE_FILES[@]}
skill_count=${#SKILL_FILES[@]}
lines=$(wc -l < "$OUTPUT_FILE" | tr -d ' ')

printf "PAI-Orbit Codex adapter\n"
printf "Output: %s\n\n" "$OUTPUT_FILE"
printf "  %d modes, %d skills → %d lines\n\n" "$mode_count" "$skill_count" "$lines"
printf "Done.\n"
